apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: get-orders
spec:
  type: git
  runtime: nodejs12
  source: kyma-functions-repo
  reference: main
  baseDir: functions/get-orders
  env:
  - name: REDIS_HOST
    value: kyma-ci-cd-redis
  - name: REDIS_PORT
    value: "6379"
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: get-orders
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    path: /.*
  service:
    host: get-orders
    name: get-orders
    port: 80
status: {}
