apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: order-created-trigger
spec:
  type: git
  runtime: nodejs12
  source: kyma-functions-repo
  reference: main
  baseDir: triggers/order-created
  env:
  - name: REDIS_HOST
    value: kyma-ci-cd-redis
  - name: REDIS_PORT
    value: "6379"
  - name: "BASE_SITE"
    value: electronics
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: order-created
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: mp-gaurav-mock-commerce-3
      type: order.created
  subscriber:
    uri: http://order-created-trigger.dev.svc.cluster.local:80/
