# In what way a pull request needs to be merged. This can be:
# * merge: creates a merge commit, combining the commits from the pull request on top of
#   the base of the pull request (default)
# * rebase: places the commits from the pull request individually on top of the base of the pull request
# * squash: combines all changes from the pull request into a single commit and places the commit on top
#   of the base of the pull request
# For more information see https://help.github.com/articles/about-pull-request-merges/
mergeMethod: rebase

# Whenever required labels are configured, pull requests will only be automatically merged whenever
# all of these labels are attached to a pull request.
requiredLabels:
- ready-for-merge